export const environment = {
  production: false,
  SSID_HIDDEN: 'Hidden network',
  ROLE_ADMIN: 'Admin',
  ROLE_SUPPORT: 'Support',
  LSK_REFRESH_TOKEN: 'apm-refresh-token',
  LSK_SERVER: 'apm-server',
  LSK_PREFERENCES: 'apm-client-preferences',
  HEADER_ALLOW_LOCAL_CACHE_NAME: 'Apm-Allow-Local-Cache',
  HEADER_ALLOW_LOCAL_CACHE_VALUE: 'Allow',
  PIN_ICON_WPA3: 'PIN_WPA3.png',
  PIN_ICON_WPA2: 'PIN_WPA2.png',
  PIN_ICON_WPA: 'PIN_WPA.png',
  PIN_ICON_WPS: 'PIN_WPS.png',
  PIN_ICON_WEP: 'PIN_WEP.png',
  PIN_ICON_NONE: 'PIN_NONE.png',
  PIN_ICON_UNKNOWN: 'PIN_UNKNOWN.png',
  LOG_INFO: true,
  LOG_ERROR: true,
  LOG_SINGLE_LEVEL: true
};