export const environment = {
  production: false,
  SSID_HIDDEN: 'Hidden network',
  ROLE_ADMIN: 'Admin',
  ROLE_SUPPORT: 'Support',
  SERVER_URL_COOKIE_NAME: "accesspointmap_server_url",
  REFRESH_TOKEN_COOKIE_NAME: "accesspointmap_refresh_token",
  PIN_ICON_WPA3: 'PIN_WPA3.png',
  PIN_ICON_WPA2: 'PIN_WPA2.png',
  PIN_ICON_WPA: 'PIN_WPA.png',
  PIN_ICON_WPS: 'PIN_WPS.png',
  PIN_ICON_WEP: 'PIN_WEP.png',
  PIN_ICON_NONE: 'PIN_NONE.png',
  PIN_ICON_UNKNOWN: 'PIN_UNKNOWN.png',
};